# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c94252dfc412de1b45c98c2953d320686b41784dc5b14619910ade28ad454eebdb6eb9a30dee4bef3633c09ff8ba350fd781f4898488a9cb54c129550ef5c55

test:
  secret_key_base: 7ea4c433717ba3927a55a2b8c57f5eae520da2e45304effbeb21e3168b4f2ff2467213167d15b3df0cf0c441e61fd1296c306e2cbedb41afb5cab2e179b2152d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
